### ISSUE TITLE
making a challenges in the games

### ISSUE THREAD

**Issue by t101804** [ElaBosak233/cloudsdale#3]
hi, currently im developing similiar like this project, did this in future not get update again? like adding challanges to each game. because in the model i see 

 ```rust
  pub title: String,
  pub description: String,
  pub category: Category,
  pub tags: Option<Vec<String>>,
  pub is_practicable: Option<bool>,
  pub is_dynamic: Option<bool>,
  pub has_attachment: Option<bool>,
  pub difficulty: Option<i64>,
  pub image_name: Option<String>,
  pub cpu_limit: Option<i64>,
  pub memory_limit: Option<i64>,
  pub duration: Option<i64>,
  pub ports: Option<Vec<i32>>,
  pub envs: Option<Vec<crate::model::challenge::Env>>,
  pub flags: Option<Vec<crate::model::challenge::Flag>>,
```

but in the front end its only question bank that can edit and add / delete

**Comment by ElaBosak233** [comment]
it used to, and this project is still under developing. because backend is under rebuilt, some functions are temporarily unable to correspond with the frontend. (in fact, the frontend is under rebuilt too, in another repository). by the way, thank u for raising this issue, im glad that i could help u. if u need further communication, u can add my contact.

**Comment by ElaBosak233** [comment]
if u want to restore category features quickly, u can refer to the repository under [this commit](https://github.com/ElaBosak233/cloudsdale/commit/3c46a71987f1c5ae69d2c8b1514249c209454412)

**Comment by ElaBosak233** [comment]
and category features were modified in [this commit](https://github.com/ElaBosak233/cloudsdale/commit/47dd4c8ff13c9f1b1dbd099fd57c9b96466ee2a9)
